### ISSUE TITLE
Production of the TnP data tree for the run range 271036-275125

### ISSUE THREAD

**Issue by HuguesBrun** [cms-analysis/MuonAnalysis-TagAndProbe#35]
- **assignee=** @folguera
- **recipe tag=** 80X-v3
- **run range =** 271036-275125
- **dataset=** /SingleMuon/Run2016B-PromptReco-v2/AOD
- **JSON file=** Cert_271036-275125_13TeV_PromptReco_Collisions16_JSON.txt
- **directory where to copy the merged trees=** /eos/cms/store/group/phys_muon/TagAndProbe/Run2016/80X_v3/data
- **recipe=**

```
cmsrel CMSSW_8_0_13 
cd CMSSW_8_0_13/src/ 
cmsenv
git cms-merge-topic battibass:stage2_L1_matching 
git clone git@github.com:HuguesBrun/MuonAnalysis-TagAndProbe.git  MuonAnalysis/TagAndProbe -b  toward-80X-v3
cd MuonAnalysis/TagAndProbe/ 
scramv1 b -j 10
```

**Comment by HuguesBrun** [comment]
@folguera, when the production is completed, please do not update the TWiki but put the name of the merged file here

**Comment by folguera** [comment]
/store/group/phys_muon/TagAndProbe/Run2016/80X_v3/data/TnPTree_80X_Run2016B_v2_GoldenJSON_Run271036to275125_incomplete.root  (98.5% efficiency)

**Comment by folguera** [comment]
{"274094": [[108, 332]], "273402": [[100, 292]], "273492": [[71, 71], [73, 282], [284, 325], [327, 338]], "274241": [[1, 46], [49, 50], [53, 285], [288, 296], [298, 361], [364, 431], [434, 473], [476, 485], [488, 837], [840, 843], [846, 865], [868, 883], [886, 999], [1002, 1127], [1132, 1133], [1136, 1152], [1161, 1176]], "275001": [[1, 1781], [1786, 2061]], "273404": [[1, 18]], "274244": [[15, 607]], "273503": [[1, 598]], "273502": [[73, 256], [258, 318], [320, 813], [815, 1064]], "273408": [[1, 6]], "273409": [[1, 309]], "274441": [[1, 431]], "274199": [[1, 623]], "275067": [[4, 233], [235, 392]], "274440": [[92, 493]], "273448": [[1, 391]], "273449": [[7, 214]], "273446": [[1, 33]], "273730": [[2, 1814], [1820, 2126]], "274161": [[1, 516]], "275068": [[1, 915]], "273302": [[1, 459]], "274388": [[1, 1730], [1732, 1820]], "274250": [[2, 701]], "274345": [[1, 170]], "273158": [[3, 1279]], "273405": [[2, 25]], "275125": [[1, 708], [710, 717], [719, 719], [721, 721], [723, 724], [726, 726], [728, 728], [730, 731], [734, 735], [737, 737], [739, 740], [742, 744], [747, 747], [750, 751], [753, 764], [768, 769], [774, 775], [778, 778], [781, 781], [783, 785], [787, 787], [789, 790], [792, 792], [795, 795], [797, 797], [799, 800], [803, 805], [815, 818], [822, 822], [824, 824], [832, 832], [834, 835], [837, 842], [848, 848], [850, 850], [856, 858], [860, 861], [866, 866], [870, 872], [876, 877], [881, 881], [883, 883], [885, 889], [891, 893], [895, 895], [897, 898], [900, 900], [902, 910], [912, 912], [915, 923], [925, 926], [928, 929], [931, 934], [936, 940], [942, 989]], "275000": [[1, 136]], "273450": [[1, 214], [219, 647]], "274317": [[1, 3]], "275124": [[106, 106], [108, 431]], "274335": [[60, 1003]], "273425": [[62, 352], [354, 733]], "274968": [[1, 160], [162, 162], [164, 174], [176, 180], [184, 186], [189, 190], [192, 192], [196, 196], [199, 199], [205, 206], [210, 211], [217, 217], [233, 233], [240, 240], [243, 243], [252, 254], [256, 263], [265, 267], [270, 276], [278, 279], [281, 287], [289, 290], [293, 293], [296, 296], [298, 298], [301, 306], [308, 309], [312, 315], [317, 317], [319, 320], [323, 324], [331, 335], [337, 340], [342, 358], [360, 362], [365, 365], [370, 370], [373, 375], [380, 380], [383, 383], [386, 386], [388, 390], [392, 397], [399, 401], [403, 404], [408, 408], [411, 411], [416, 416], [425, 425], [433, 433], [440, 440], [450, 451], [455, 455], [457, 458], [460, 460], [462, 465], [468, 468], [473, 473], [475, 480], [482, 483], [485, 485], [487, 487], [490, 491], [494, 496], [499, 500], [502, 505], [510, 514], [516, 516], [518, 518], [520, 520], [522, 522], [524, 533], [535, 555], [557, 593], [595, 598], [600, 610], [612, 627], [630, 641], [643, 643], [645, 651], [653, 686], [688, 722], [724, 761], [763, 765], [767, 832], [834, 915], [917, 1015], [1017, 1124], [1126, 1144], [1147, 1176], [1178, 1192]], "274969": [[1, 140], [142, 150], [152, 152], [156, 156], [158, 158], [160, 161], [164, 164], [166, 167], [169, 169], [173, 174], [176, 176], [184, 184], [191, 191], [194, 194], [205, 205], [212, 212], [215, 215], [218, 218], [220, 220], [236, 238], [244, 244], [246, 247], [249, 252], [255, 258], [260, 269], [271, 274], [278, 279], [281, 281], [285, 300], [302, 314], [316, 330], [332, 381], [383, 392], [395, 421], [424, 480], [485, 488], [490, 618], [621, 635], [637, 644], [647, 702], [705, 830], [833, 957], [960, 1003]], "273406": [[1, 112]], "273411": [[1, 29]], "273410": [[1, 90]], "274337": [[3, 17]], "274336": [[1, 14]], "273403": [[1, 53]], "274319": [[1, 225]], "274251": [[1, 546]], "274146": [[4, 67]], "274316": [[1, 959]], "274315": [[2, 90], [92, 173], [175, 219], [221, 375], [377, 424]], "273728": [[2, 100]], "274339": [[1, 25], [27, 27], [36, 93]], "273725": [[83, 252], [254, 2545]], "274338": [[1, 698]], "275074": [[1, 442], [444, 647]], "274442": [[1, 256], [258, 752]], "274421": [[1, 342]], "274420": [[94, 268]], "275059": [[78, 81], [105, 133], [135, 137]], "274422": [[1, 2207]], "274999": [[1, 1241]], "274998": [[64, 240], [242, 782]], "273554": [[77, 437]], "273555": [[1, 173]], "273447": [[1, 113], [115, 412]], "274283": [[2, 19]], "274284": [[1, 210]], "274198": [[81, 191]], "273493": [[4, 233]], "274286": [[1, 34], [36, 41], [43, 51], [53, 54], [58, 61], [64, 70], [72, 76], [79, 83], [85, 95], [99, 99], [102, 102], [109, 110], [134, 134], [137, 137]], "274240": [[1, 40], [42, 82]], "273494": [[1, 192]], "274200": [[5, 678]], "274344": [[6, 632]], "274954": [[37, 37], [39, 57]], "274159": [[1, 43]], "275073": [[1, 517]], "274172": [[31, 95]], "274955": [[1, 91]], "274382": [[94, 144]], "274387": [[88, 439]], "274160": [[1, 207]], "274971": [[1, 905]], "274970": [[1, 47]]}
