### ISSUE TITLE
Production of the JPsi TnP data tree for the run range 275126-275783 

### ISSUE THREAD

**Issue by battibass** [cms-analysis/MuonAnalysis-TagAndProbe#37]
**assignee=** @lecriste
**recipe tag=** 80X-v2
**run range=** 275126-275783
**dataset=** /Charmonium/Run2016B-PromptReco-v2/AOD (until run 275376 included) /Charmonium/Run2016C-PromptReco-v2/AOD
**JSON file=** Cert_271036-276097_13TeV_PromptReco_Collisions16_JSON_NoL1T.txt
    directory where to copy the merged trees= /eos/cms/store/group/phys_muon/TagAndProbe/Run2016/80X_v2/jpsi/data
**recipe=** 80X_v2, the one used in past iterations

**Comment by lecriste** [comment]
The trees are completed.
They cover the full JSON file run range.

**Comment by battibass** [comment]
Thanks! could you also update the TWIKI if not already done?
