### ISSUE TITLE
To up with July 15th Golden JSON file 

### ISSUE THREAD

**Issue by HuguesBrun** [cms-analysis/MuonAnalysis-TagAndProbe#38]
- **assignee=** @KyeongPil-Lee
- **recipe tag=** 80X-v3
- **run range =**  276098-276384
- **dataset=** /SingleMuon/Run2016C-PromptReco-v2/AOD _(until run 276314 included)_ and  /SingleMuon/Run2016D-PromptReco-v2/AOD _(from run 276315)_
- **JSON file=** Cert_271036-276384_13TeV_PromptReco_Collisions16_JSON_NoL1T.txt
- **directory where to copy the merged trees=** /eos/cms/store/group/phys_muon/TagAndProbe/Run2016/80X_v3/data
- **recipe=**

```
cmsrel CMSSW_8_0_13 
cd CMSSW_8_0_13/src/ 
cmsenv
git cms-merge-topic battibass:stage2_L1_matching 
git clone git@github.com:HuguesBrun/MuonAnalysis-TagAndProbe.git  MuonAnalysis/TagAndProbe -b  toward-80X-v3
cd MuonAnalysis/TagAndProbe/ 
scramv1 b -j 10
```

**Comment by battibass** [comment]
Thanks a lot @KyeongPil-Lee
