### ISSUE TITLE
Production of the TnP trees for Run G and recipe 80X-v4

### ISSUE THREAD

**Issue by HuguesBrun** [cms-analysis/MuonAnalysis-TagAndProbe#45]
- **assignee=** @folguera 
- **recipe tag=** 80X-v4
- **run range =**  278819-280385
- **dataset=** /SingleMuon/Run2016G-PromptReco-v1/AOD
- **JSON file=** Cert_271036-280385_13TeV_PromptReco_Collisions16_JSON_NoL1T.txt
- **directory where to copy the merged trees=** /eos/cms/store/group/phys_muon/TagAndProbe/Run2016/80X_v4/data/RunG
- **recipe=**

```
cmsrel CMSSW_8_0_20 
cd CMSSW_8_0_20/src/ 
cmsenv
git cms-merge-topic battibass:stage2_L1_matching_80X 
git clone git@github.com:HuguesBrun/MuonAnalysis-TagAndProbe.git  MuonAnalysis/TagAndProbe -b  toward-80X-v4
cd MuonAnalysis/TagAndProbe/ 
scramv1 b -j 10
```

**Comment by folguera** [comment]
Done, 100% completed.  File can be found at: 
/store/group/phys_muon/TagAndProbe/Run2016/80X_v4/data/RunG/TnPTree_80X_Run2016G_GoldenJSON_Run278819-280385.root

**Comment by HuguesBrun** [comment]
Many thanks @folguera,
I updated the TWiki including your trees:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/MuonTagAndProbeTreesRun2
