### ISSUE TITLE
Production of the TnP trees for Run B to F and recipe 80X-v5

### ISSUE THREAD

**Issue by HuguesBrun** [cms-analysis/MuonAnalysis-TagAndProbe#50]
- **assignee=** @KyeongPil-Lee 
- **recipe tag=** 80X-v5
- **run range =**  273158-278808
- **dataset=** /SingleMuon/Run2016B-23Sep2016-v3/AOD, /SingleMuon/Run2016C-23Sep2016-v1/AOD, /SingleMuon/Run2016D-23Sep2016-v1/AOD, /SingleMuon/Run2016E-23Sep2016-v1/AOD, /SingleMuon/Run2016F-23Sep2016-v1/AOD
- **JSON file=** Cert_271036-284044_13TeV_PromptReco_Collisions16_JSON_NoL1T.txt
- **directory where to copy the merged trees=** /eos/cms/store/group/phys_muon/TagAndProbe/Run2016/80X_v5/data/run[B,C,D,E,F]
- **recipe=**

```
cmsrel CMSSW_8_0_20 
cd CMSSW_8_0_20/src/ 
cmsenv
git cms-merge-topic battibass:stage2_L1_matching_80X 
git clone git@github.com:cms-analysis/MuonAnalysis-TagAndProbe.git  MuonAnalysis/TagAndProbe -b  80X-v5
cd MuonAnalysis/TagAndProbe/ 
scramv1 b -j 10
```

**Comment by KyeongPil-Lee** [comment]
(I add HD and Benjamin to cc)

Dear Hugues,

I have started the production.

Best Regards,
Kyeongpil

On 10 Nov 2016, at 2:21 PM, Hugues BRUN <notifications@github.com<mailto:notifications@github.com>> wrote:
-   assignee= @KyeongPil-Leehttps://github.com/KyeongPil-Lee
-   recipe tag= 80X-v5
-   run range = 273158-278808
-   dataset= /SingleMuon/Run2016B-23Sep2016-v3/AOD, /SingleMuon/Run2016C-23Sep2016-v1/AOD, /SingleMuon/Run2016D-23Sep2016-v1/AOD, /SingleMuon/Run2016E-23Sep2016-v1/AOD, /SingleMuon/Run2016F-23Sep2016-v1/AOD
-   JSON file= Cert_271036-284044_13TeV_PromptReco_Collisions16_JSON_NoL1T.txt
-   directory where to copy the merged trees= /eos/cms/store/group/phys_muon/TagAndProbe/Run2016/80X_v5/data/run[B,C,D,E,F]
-   recipe=

cmsrel CMSSW_8_0_20
cd CMSSW_8_0_20/src/
cmsenv
git cms-merge-topic battibass:stage2_L1_matching_80X
git clone git@github.commailto:git@github.com:cms-analysis/MuonAnalysis-TagAndProbe.git  MuonAnalysis/TagAndProbe -b  80X-v5
cd MuonAnalysis/TagAndProbe/
scramv1 b -j 10

**Comment by BenjaminRS** [comment]
Thanks Kyeongpil!

**Comment by KyeongPil-Lee** [comment]
Dear conveners,

TnP Tree production for Rereco dataset is finished and all of them are uploaded in eos directory.
In the case of RunB, only two jobs are continuously failed among 2613 jobs, so they are not included. Missing jobs are less then 0.1%.
I attached the json file with missing runs in RunB. Other TnP trees contains all statistics without failed job.

Best Regards,
Kyeongpil

On 10 Nov 2016, at 5:45 PM, Kyeongpil Lee <kyeongpil.lee@cern.ch<mailto:kyeongpil.lee@cern.ch>> wrote:

(I add HD and Benjamin to cc)

Dear Hugues,

I have started the production.

Best Regards,
Kyeongpil

On 10 Nov 2016, at 2:21 PM, Hugues BRUN <notifications@github.com<mailto:notifications@github.com>> wrote:
-   assignee= @KyeongPil-Leehttps://github.com/KyeongPil-Lee
-   recipe tag= 80X-v5
-   run range = 273158-278808
-   dataset= /SingleMuon/Run2016B-23Sep2016-v3/AOD, /SingleMuon/Run2016C-23Sep2016-v1/AOD, /SingleMuon/Run2016D-23Sep2016-v1/AOD, /SingleMuon/Run2016E-23Sep2016-v1/AOD, /SingleMuon/Run2016F-23Sep2016-v1/AOD
-   JSON file= Cert_271036-284044_13TeV_PromptReco_Collisions16_JSON_NoL1T.txt
-   directory where to copy the merged trees= /eos/cms/store/group/phys_muon/TagAndProbe/Run2016/80X_v5/data/run[B,C,D,E,F]
-   recipe=

cmsrel CMSSW_8_0_20
cd CMSSW_8_0_20/src/
cmsenv
git cms-merge-topic battibass:stage2_L1_matching_80X
git clone git@github.commailto:git@github.com:cms-analysis/MuonAnalysis-TagAndProbe.git  MuonAnalysis/TagAndProbe -b  80X-v5
cd MuonAnalysis/TagAndProbe/
scramv1 b -j 10

**Comment by HuguesBrun** [comment]
Hello @KyeongPil-Lee, 
Thank you very much ! 
Could I ask you put the attachment directly in the [GitHub ticket](https://github.com/cms-analysis/MuonAnalysis-TagAndProbe/issues/50) ? I think that it did not work through the mail...

**Comment by KyeongPil-Lee** [comment]
I attachted the json (github doesn't support .json so it is converted to .txt file)

[notFinishedLumis.json.txt](https://github.com/cms-analysis/MuonAnalysis-TagAndProbe/files/598960/notFinishedLumis.json.txt)

**Comment by HuguesBrun** [comment]
Hello @KyeongPil-Lee , 
I just updated the TWiki, I let you double check that I did not do any mistake 
Many thanks

**Comment by KyeongPil-Lee** [comment]
Dear Hugues,

I think all information is fine except for one small thing that only RunB has missing jobs (less than 0.1%) and the other run era (C,D,E and F) contains full statistics (no failed jobs).

Best Regards,
Kyeongpil

On 24 Nov 2016, at 4:21 AM, Hugues BRUN <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @KyeongPil-Lee<https://github.com/KyeongPil-Lee> ,
I just updated the TWiki, I let you double check that I did not do any mistake
Many thanks

**Comment by HuguesBrun** [comment]
fixed, thanks !

**Comment by gpetruc** [comment]
Is there going to be an update of the trees also for the J/Psi to measure the reco & loose id efficiency at low pT?
